language: java
jdk:
  - oraclejdk8
script:
  - mvn clean install -Pqulice
before_install:
  - pip install --user codecov
after_success:
  - codecov
  - mvn clean cobertura:cobertura coveralls:report -DrepoToken=$REPO_TOKEN
