language: java
jdk:
  - oraclejdk8
script:
  - mvn clean install -Pqulice
before_install:
  - pip install --user codecov
after_success:
  - cat target/site/jacoco/jacoco.xml
  - codecov --dump
  - mvn clean test jacoco:report cobertura:cobertura coveralls:report -Pqulice -DrepoToken=$REPO_TOKEN
