language: java
dist: trusty
jdk:
  - oraclejdk8
script:
  - mvn clean install -Pqulice
after_success:
  - mvn clean test jacoco:report cobertura:cobertura coveralls:report -Pqulice -DrepoToken=$REPO_TOKEN
