language: java
jdk:
  - oraclejdk8
script:
  - mvn clean install -Pqulice
before_install:
  - pip install --user codecov
after_success:
  - cat /home/travis/build/piotrkot/simple-cli/target/site/jacoco/jacoco.xml
  - bash <(curl -s https://codecov.io/bash) -d
  - codecov --dump
  - mvn clean test jacoco:report cobertura:cobertura coveralls:report -Pqulice -DrepoToken=$REPO_TOKEN
